__: aircloud
# SNS settings
# 一些社交平台地址，支持以下几种：
weibo_username: 3286578617
zhihu_username: ai-er-lan-xue-da
github_username: AirCloud
twitter_username: iconie_alloy
facebook_username: xiaotao.nie.5
linkedin_username: 小涛-聂-80964aba
